/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-HL7.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : HL7
 #	author : miyako
 #	2022/06/05
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-HL7.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- HL7
            
			case 1 :
				HL7_Parse(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

#include <regex>
#include <exception>

static void unescape(std::string& value) {

    // Compiled once (function-local static, thread-safe init per C++11) instead of
    // re-compiling all 8 patterns on every call - this runs once per HL7 field/
    // component/subcomponent value, so a single message can invoke it hundreds of times.
    static const std::regex reF("\\\\F\\\\");
    static const std::regex reR("\\\\R\\\\");
    static const std::regex reS("\\\\S\\\\");
    static const std::regex reT("\\\\T\\\\");
    static const std::regex reBr("\\\\\\.br\\\\");
    static const std::regex reX0A("\\\\X0A\\\\");
    static const std::regex reX0D("\\\\X0D\\\\");
    static const std::regex reE("\\\\E\\\\");

    value = std::regex_replace(value, reF, "|");
    value = std::regex_replace(value, reR, "~");
    value = std::regex_replace(value, reS, "^");
    value = std::regex_replace(value, reT, "&");

    value = std::regex_replace(value, reBr, "\r");
    value = std::regex_replace(value, reX0A, "\n");
    value = std::regex_replace(value, reX0D, "\r");

    value = std::regex_replace(value, reE, "\\");
}

static void push_value(PA_CollectionRef c, HL7_Node *node) {
    
    std::string value = std::string(node->element.value, node->element.length);
    unescape(value);
    
    C_TEXT t;
    t.setUTF8String((const uint8_t *)value.c_str(), value.length());
    PA_Variable v = PA_CreateVariable(eVK_Unistring);
    PA_Unistring u = PA_CreateUnistring((PA_Unichar *)t.getUTF16StringPtr());
    PA_SetStringVariable(&v, &u);
    PA_SetCollectionElement(c, PA_GetCollectionLength(c), v);
    PA_ClearVariable(&v);
}

// ob_set_c() only has a wide-key (const wchar_t*) overload at the project's v1.0.1 tag
// (confirmed against support/4DPlugin-JSON.h fetched at that exact ref - there is no
// narrow-key sibling there, unlike ob_set_s). fieldName is a runtime UTF-8 std::string
// (the HL7 segment ID, read from the message), not a literal, so it can't just take an
// L prefix like the other keys below - it needs an actual conversion. This reuses the
// file's own existing C_TEXT UTF-8->UTF-16 conversion (already used in push_value above)
// and widens each UTF-16 code unit into the destination wstring's wchar_t: exact on
// Windows (wchar_t is itself UTF-16 there), and correct for the BMP on macOS (wchar_t is
// UTF-32 there, but a lone UTF-16 code unit's numeric value equals its UTF-32 codepoint
// for any character outside the surrogate-pair range, which covers realistic HL7 segment
// IDs). This avoids the width mismatch a direct PA_Unichar*->wchar_t* reinterpret-cast
// would introduce specifically on macOS.
static std::wstring to_wide_key(const std::string &s) {
    C_TEXT t;
    t.setUTF8String((const uint8_t *)s.c_str(), (uint32_t)s.length());
    const PA_Unichar *u16 = t.getUTF16StringPtr();
    uint32_t len = t.getUTF16Length();
    std::wstring out;
    if (u16 != 0 && len > 0) {
        out.assign(u16, u16 + len);
    }
    return out;
}

static void print_node(PA_ObjectRef hl7, HL7_Node *node, HL7_Element_Type element_type)
{
    if(node != 0) {
                
        PA_CollectionRef c = PA_CreateCollection();
        
        std::string fieldName;
        
        do
        {
            if (node->element.length > 0) {
                    
                if(element_type == HL7_ELEMENT_FIELD) {
                    if(fieldName.length() == 0) {
                        fieldName = std::string(node->element.value, node->element.length);
                    }else{
                        push_value(c, node);
                    }
                }else{
                    push_value(c, node);
                }
  
            }

            if (node->children != 0) {
                
                    PA_ObjectRef o = PA_CreateObject();
                    print_node(o, node->children, hl7_child_type(element_type));
                    PA_Variable v = PA_CreateVariable(eVK_Object);
                    PA_SetObjectVariable(&v, o);
                    PA_SetCollectionElement(c, PA_GetCollectionLength(c), v);
                    PA_ClearVariable(&v);
 
            }
            node = node->sibling;
            
        } while (node != 0);
        
        switch (element_type) {
            case HL7_ELEMENT_SUBCOMPONENT:
                ob_set_c(hl7, L"subcomponent", c);
                break;
            case HL7_ELEMENT_COMPONENT:
                ob_set_c(hl7, L"component", c);
                break;
            case HL7_ELEMENT_REPETITION:
                ob_set_c(hl7, L"repetition", c);
                break;
            case HL7_ELEMENT_FIELD:
                {
                    std::wstring wFieldName = to_wide_key(fieldName);
                    ob_set_c(hl7, wFieldName.c_str(), c);
                }
                break;
            case HL7_ELEMENT_SEGMENT:
                ob_set_c(hl7, L"HL7", c);
                break;
            case HL7_ELEMENT_TYPE_COUNT:
                ob_set_c(hl7, L"count", c);
                break;
            default:
                break;
        }
    }
}

static void print_message(PA_ObjectRef hl7, HL7_Message *message) {
    
    if(message != 0) {
        print_node(hl7, message->head, HL7_ELEMENT_SEGMENT);
    }
    
}

void HL7_Parse(PA_PluginParameters params) {

    PA_ObjectRef status = PA_CreateObject();
    
    PackagePtr pParams = (PackagePtr)params->fParameters;
    
    ob_set_b(status, L"success", false);

    C_TEXT t;
    t.fromParamAtIndex(pParams, 1);
    
    CUTF8String u8;
    t.copyUTF8String(&u8);
    
    HL7_Settings settings;
    hl7_settings_init(&settings);
    
    HL7_Buffer input_buffer;
    size_t message_length = u8.length();
    
    hl7_buffer_init(&input_buffer, (char *)u8.c_str(), message_length);
    hl7_buffer_move_wr_ptr(&input_buffer, message_length);
    
    HL7_Allocator allocator;
    HL7_Message message;
    
    hl7_allocator_init(&allocator, malloc, free);
    hl7_message_init(&message, &settings, &allocator);

    HL7_Parser parser;
    
    hl7_parser_init(&parser, &settings);
    
    // hl7_parser_read() itself is a plain-C call and won't throw, but building the
    // result (print_message walking every segment/field/component and allocating
    // std::string/PA_* values along the way) can throw (e.g. std::bad_alloc on a
    // very large message). This command has a declared return value (manifest:
    // "HL7 Parse(&T):J"), so letting that exception propagate up to PluginMain's
    // catch(...) would skip PA_ReturnObject entirely and hang the host waiting for
    // a result that never comes - and it would also skip every _fini call below,
    // leaking the whole parsed node tree. Catching locally guarantees both the
    // native cleanup and the return always happen.
    try
    {
        if (hl7_parser_read(&parser, &message, &input_buffer) == 0) {
            ob_set_b(status, L"success", true);
            print_message(status, &message);
        }
    }
    catch (const std::exception &e)
    {
        ob_set_b(status, L"success", false);
        ob_set_s(status, L"error", e.what());
    }
    catch (...)
    {
        ob_set_b(status, L"success", false);
        ob_set_s(status, L"error", "unknown error while parsing HL7 message");
    }

    hl7_parser_fini(&parser);
    hl7_message_fini(&message);
    hl7_allocator_fini(&allocator);
    hl7_buffer_fini(&input_buffer);
    hl7_settings_fini(&settings);
    
    PA_ReturnObject(params, status);
}
