/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-HL7.h
 #	source generated by 4D Plugin Wizard
 #	Project : HL7
 #	author : miyako
 #	2022/06/05
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_HL7_H
#define PLUGIN_HL7_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#include "4DPlugin-JSON.h"

#include <hl7parser/buffer.h>
#include <hl7parser/defs.h>
#include <hl7parser/element.h>
#include <hl7parser/message.h>
#include <hl7parser/parser.h>
#include <hl7parser/token.h>
#include <hl7parser/settings.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#pragma mark -

void HL7_Parse(PA_PluginParameters params);

#endif /* PLUGIN_HL7_H */
